name = "WalkingSim"
uuid = "b8755482-2c48-4b3d-bf2d-540462af5300"
authors = ["Anastasia Paramonova"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
